# Generated by Django 3.2.15 on 2022-11-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservice_app', '0003_alter_nursery_nursery_regid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='nursery_regid',
            field=models.CharField(max_length=10),
        ),
    ]
